### ISSUE TITLE
Billing info required everytime you're adding a course

### ISSUE THREAD

**Issue by syrinehamza** [moar55/se-project-testing#73] opened 2017-05-01 21:16 UTC
1- Severity High
2- reported by Syrine Hamza
3- when I want to post a course as a service provider, it ask for the biilling info everytime
4- login as a service provider, and add a course, then logout and re-add a course
5- The service provider should enter his info once and be able to edit them for example or something similar but not re-entering them everytime

**Comment by safya-alzayat** [comment] 2017-05-01 21:19
duplicate of https://github.com/moar55/se-project-testing/issues/33

**Closed as completed by safya-alzayat** 2017-05-01 21:19 UTC
