### ISSUE TITLE
Student cannot add courses

### ISSUE THREAD

**Issue by NardineSanad** [moar55/se-project-testing#61] opened 2017-05-01 20:15 UTC
1- Severity high
2- reported by Nardine Nader
3- Description: a student should be able to add a course to be later viewed in the students profile
4- Steps: view service providers profile and add a course from them
5- Expected results: there should be an option to select a course and then it should appear in the students profile

**Comment by moar55** [comment] 2017-05-01 21:53
You mean a service provider, and this is a duplicate issue of #3 .
Please check the issues before adding new ones. We have 59 issues now !

**Comment by NardineSanad** [comment] 2017-05-01 22:02
no I mean as a student , the student has a courses section in his profile, how is he able to fill that ?

**Comment by safya-alzayat** [comment] 2017-05-01 22:37
sorry it is still a duplicate of https://github.com/moar55/se-project-testing/issues/20

**Closed as completed by safya-alzayat** 2017-05-01 22:37 UTC
