### ISSUE TITLE
Invalid values when editing profile as a service provider: mobile number

### ISSUE THREAD

**Issue by sondoskamel** [moar55/se-project-testing#55] opened 2017-05-01 20:09 UTC
Severity: Medium
Reported By: Sondos Kamel
Description: Mobile number can be edited into invalid values (symbols and letters)
Steps to produce the issue:

1. Login as a service provider
2. Choose to edit general info
3. Enter symbols and/or letters to mobile number
4. Click on submit

Expected result: An alert saying that mobile number should consist of numbers only

**Comment by safya-alzayat** [comment] 2017-05-01 21:55
duplicate of https://github.com/moar55/se-project-testing/issues/75

**Closed as completed by safya-alzayat** 2017-05-01 21:55 UTC
