### ISSUE TITLE
Students cant match to any courses

### ISSUE THREAD

**Issue by shadyaboud96** [moar55/se-project-testing#28] opened 2017-05-01 19:07 UTC
1- high
2- Reported by Shady Aboud
3- a student cant view any courses so they can match with.
4- log in as a student and try to view the courses and then we will see if there is a capability to match or not.
5- the courses should be viewed

**Comment by safya-alzayat** [comment] 2017-05-01 20:23
duplicate of https://github.com/moar55/se-project-testing/issues/16

**Closed as completed by safya-alzayat** 2017-05-01 20:23 UTC
