### ISSUE TITLE
add course doesn't work

### ISSUE THREAD

**Issue by mireille-adel** [moar55/se-project-testing#74] opened 2017-05-01 21:23 UTC
1: severity: high 
2: Reported by: Mireille Ayoub
3: Description: As the service provider can't add courses hence the admin can't view the events
4: Steps: 
1. login admin 
2.  service provider register
3. admin verify the service provider 
4. add courses

**Comment by safya-alzayat** [comment] 2017-05-01 21:33
duplicate of https://github.com/moar55/se-project-testing/issues/3

**Closed as completed by safya-alzayat** 2017-05-01 21:33 UTC
