### ISSUE TITLE
Stuck in the service provider's profile

### ISSUE THREAD

**Issue by shadyaboud96** [moar55/se-project-testing#58] opened 2017-05-01 20:11 UTC
1- high
2- Reported by Shady Aboud
3- There is no buttons to take you back since you're in a company profile. No any other options than the follow button. Follow or die there, after you followed them you'll also die there.
4- Log in as a student search for a company by its name and choose 'business' from the radio buttons and then click on the name of the company.
5- There should be any button to take you back.

**Comment by safya-alzayat** [comment] 2017-05-01 20:25
duplicate of https://github.com/moar55/se-project-testing/issues/51

**Closed as completed by safya-alzayat** 2017-05-01 20:25 UTC
