### ISSUE TITLE
As a service provider i cant view my courses

### ISSUE THREAD

**Issue by shadyaboud96** [moar55/se-project-testing#43] opened 2017-05-01 19:32 UTC
1- medium
2- Reported by Shady Aboud
3- as a service provider i should be able to view my courses. However i cant.
4- Log in as a service provider and try viewing the courses you have. You'll not be able to view them because they're not added.
5- A service provider should be able to view his courses.

**Comment by safya-alzayat** [comment] 2017-05-01 19:38
duplicate of https://github.com/moar55/se-project-testing/issues/3

**Closed as completed by safya-alzayat** 2017-05-01 19:38 UTC

**Comment by shadyaboud96** [comment] 2017-05-01 20:39
Unfortunately, its not a duplicate. #3 says that as a service provider he cant add a course. However, here i'm saying that i cant view my courses that i've added. Thus, if #3 were solved how will i view them?

**Comment by safya-alzayat** [comment] 2017-05-01 21:34
if the courses were added the service provider would have been able to view them on his/her homepage
