### ISSUE TITLE
Console.log

### ISSUE THREAD

**Issue by syrinehamza** [moar55/se-project-testing#42] opened 2017-05-01 19:26 UTC
1- Severity High
2- reported by Syrine Hamza
3- There are too much console.log overwhelming the terminal, and they are not descriprive messages
4- when clicking on almost everything..
5- remove/more descriptive console.log

**Comment by safya-alzayat** [comment] 2017-05-01 19:40
duplicate of https://github.com/moar55/se-project-testing/issues/8

**Closed as completed by safya-alzayat** 2017-05-01 19:40 UTC
