### ISSUE TITLE
student cannot view events

### ISSUE THREAD

**Issue by mahmoud-abdalla** [moar55/se-project-testing#57] opened 2017-05-01 20:10 UTC
1: Severity (high)

2: Reported by
Mahmoud Yasser

3: Description
Students cannot view events or even search for it. 

4: Steps to reproduce issue: nothing enter the site and you will find nothing that even resembles an event

5: Expected result
the ability to view events

**Comment by safya-alzayat** [comment] 2017-05-01 20:20
duplicate of https://github.com/moar55/se-project-testing/issues/46

**Closed as completed by safya-alzayat** 2017-05-01 20:20 UTC
