### ISSUE TITLE
update student info - delete interest

### ISSUE THREAD

**Issue by dyanni** [moar55/se-project-testing#32] opened 2017-05-01 19:11 UTC
1-Severity: Medium
2-Reported by: Daniel Yanni
3- Description: When a student tries to delete an empty interest he/she created. It will not be deleted. 
4- Steps to reproduce the issue: 1- login as a student 2- my profile 3- choose an empty interest. 4- submit. 
5- Expected Result: Interest should be deleted.

**Comment by safya-alzayat** [comment] 2017-05-01 21:16
duplicate of https://github.com/moar55/se-project-testing/issues/70

**Closed as completed by safya-alzayat** 2017-05-01 21:16 UTC
