### ISSUE TITLE
need to search for empty space to see the businesses

### ISSUE THREAD

**Issue by syrinehamza** [moar55/se-project-testing#69] opened 2017-05-01 21:04 UTC
1- Severity High
2- reported by Syrine Hamza
3- when I want to see the businesses as a client i have to do an empty search
4- login as a student and search and empty space a service provider profile
5- The student should be able to see the companies and others without clicking on anything or in a home page

**Comment by safya-alzayat** [comment] 2017-05-01 21:05
duplicate of https://github.com/moar55/se-project-testing/issues/1

**Closed as completed by safya-alzayat** 2017-05-01 21:05 UTC
