### ISSUE TITLE
Invalid values added to interests by students

### ISSUE THREAD

**Issue by sondoskamel** [moar55/se-project-testing#21] opened 2017-05-01 18:56 UTC
Severity: Medium
Reported By: Sondos Kamel
Description: Invalid values (symbols, numbers, empty box) are successfully added to interests
Steps to produce the issue:

1. Login as a student
2. Choose to edit general info
3. Don't enter anything in the add interest text box or add symbols or numbers only
4. Click on add interest
5. Interest appears on the student's profile

Expected result: An alert saying to enter a valid interest

**Comment by safya-alzayat** [comment] 2017-05-01 23:15
duplicate of #30

**Closed as completed by safya-alzayat** 2017-05-01 23:15 UTC
